name: a489_map_converter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
